# Defines a list of applications that are exempt from standard audio recording restrictions.
# Format: package_name:audio_source_id
#
# Common audio_source_id values:
# 1: AUDIO_SOURCE_MIC
# 7: AUDIO_SOURCE_VOICE_COMMUNICATION
# 1999: AUDIO_SOURCE_HOTWORD
com.motorola.callassistant:7
com.lenovo.xiaotian.trigger:1999
com.android.systemui:1
com.android.systemui:7