# open log or not
LOG_FILE_OPEN : 1

# 解析用的模板文件
GRAMMAR_TEMPLATE : template/time_template.xml

# 预处理用的归一化文件
REGEX_NORMAL : normal/time_regex_rule_normal

# 万年历
CALENDAR_DICT : dict/calendar.dict

# 槽位归一化文件
GRAMMAR_NORMAL : template/slot_normal

# 数字处理词典 
CHINESE2ARAB_DICT : dict/chinese2arab
CHINESE2SERL_DICT : dict/chinese2serl

# 热配置开关 0关闭热配置，1打开热配置
USE_RELOAD : 1

# 输出方式 0旧方式，1新结构
USE_NEW_TIME : 1

# 是否固定时间
USE_CONF_BASE_TIME : 0
BASE_YEAR : 2018
BASE_MONTH : 3
BASE_DAY : 31
BASE_HOUR : 10
BASE_MINUTE : 30
BASE_SECOND : 3
